# Generated by Django 4.2.1 on 2023-10-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
